---
apiVersion: v1
kind: Service
metadata:
  name: garlaxy-frontend
spec:
  selector:
    app: garlaxy
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
...
